name: BlocksmithShowcase
version: 1.0.0
main: io.papermc.blocksmith.BlocksmithShowcase
description: Blocksmith's showcase
author: alienworld1
website: https://github.com/alienworld1/blocksmith-showcase
api-version: "1.21" 
depend: [Multiverse-Core]

permissions:
  permission.blocksmith.admin:
    description: "blocksmith admin"
    default: op

  permission.blocksmith.builder:
    description: "blocksmith builder"
    default: notop

commands:
  blocksmith:
    description: "blocksmith's showcase command"
    usage: "/blocksmith"
    aliases: [blocksmith, bs]
    permission: permission.blocksmith.admin
    permission-message: "You do not have permission to use this command!"
  
  breakable:
    description: "protect blocks from being broken"
    usage: "/breakable <args>"
    aliases: [breakable, br]
    permission: permission.blocksmith.admin
    permission-message: "You do not have permission to use this command!"

  nick:
    description: "set nickname of a player"
    usage: "/nick <nick_name>"
    aliases: [nick, nickname]
    permission: permission.blocksmith.builder
    permission-message: "You do not have permission to use this command!"